# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 15 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
gems: [jekyll-paginate]
#markdown: Redcarpet
markdown: kramdown

title: YJ的博客
description:
author:
  name: YJ
  email: cj.yangjun@gmail.com
  github: yangjunsss
  linkedin: yj-chen-0525b8104
  twitter:
  pinterest:
  bio: 一晃做了十年的技术人，保持着知识的饥渴，记录点个人的薄见，请保持客观和怀疑看文章，您来了就是客人，我以礼相待
  anu:
  email_md5:

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
